/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vDasT9pw2wXuKg1JAx8T5e

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: vDasT9pw2wXuKg1JAx8T5e/projectModule

import projectcss from "./plasmic.module.css"; // plasmic-import: vDasT9pw2wXuKg1JAx8T5e/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
